spring:
  application:
    name: realworld
  security:
     jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000 # a day
        refresh-token:
         expiration: 604800000 # 7 days
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://localhost:3306/realworld?serverTimezone=UTC
    username: springstudent
    password: springstudent

  server:
    port: 8080


  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
      database: mysql

